### ISSUE TITLE
Variable interpolation

### ISSUE THREAD

**Issue by bryanbuchanan** [bajrangCoder/zed-scss#1]
Thank you for the extension!

This may be an edge case, but variable interpolation appears to break the syntax highlighting.

Example:

```scss
color: $color; // Correct formatting
color: #{$color}; // Breaks formatting
color: $color; // Incorrect formatting
```
