### ISSUE TITLE
Bug in highlighting

### ISSUE THREAD

**Issue by jodaka** [bajrangCoder/zed-scss#2]
Below is an piece of SCSS and screenshot of how it looks in Zed
```css
@import 'styles/form';

*, *:after, *:before {
  box-sizing: border-box;
}

a, p {
  word-break: break-word;
}

html {
  -webkit-font-smoothing: antialiased;
  scroll-behavior: auto;
  font-size: 4px;
  height: 100%;
}

body {
  @mixin body_long_14;
  margin: 0;
  background-color: #ffffff;
  color: var(--c-dark);
  height: 100%;
}

button {
  color: var(--c-text-default);
}

#app {
  display: flex;
  flex-direction: column;
  height: 100%;
}
```

selector colors are inconsistent and rules inside of body selectors seems to be completely off
<img width="776" alt="image" src="https://github.com/bajrangCoder/zed-scss/assets/83644/f80efc7f-8c99-42ed-acde-6279a5cd739d">
